openapi: 3.0.0
info:
  title: Dewi
  version: 1.0.0
servers:
  - url: https://130.162.195.228
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Auth
  - name: Product
  - name: Category
  - name: Supplier
paths:
  /mhs714220002/api/v1/register:
    post:
      tags:
        - Auth
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: Dewww
                password: dewi12345
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /mhs714220002/api/v1/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: Dewww
                password: dewi12345
      security:
        - noauthAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /mhs714220002/api/v1/products:
    get:
      tags:
        - Product
      summary: GetProduct
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Product
      summary: PostProduct
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: HP
                description: RAM 12/526
                price: 3000000
                category_id: 4
                supplier_id: 4
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /mhs714220002/api/v1/products/{id}:
    get:
      tags:
        - Product
      summary: GetProductByID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - Product
      summary: PutProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: HP
                description: RAM 12/526
                price: 3500000
                category_id: 4
                supplier_id: 4
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Product
      summary: DeleteProduct
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /mhs714220002/api/v1/categories:
    get:
      tags:
        - Category
      summary: GetCategory
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Category
      summary: PostCategory
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Gaming
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /mhs714220002/api/v1/categories/{id}:
    get:
      tags:
        - Category
      summary: GetCategoryByID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - Category
      summary: PutCategory
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Game
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Category
      summary: DeleteCategory
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /mhs714220002/api/v1/suppliers:
    get:
      tags:
        - Supplier
      summary: GetSupplier
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Supplier
      summary: PostSupplier
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                Name: Rezz
                Email: rez@gmail.com
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /mhs714220002/api/v1/suppliers/{id}:
    get:
      tags:
        - Supplier
      summary: GetSupplierByID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - Supplier
      summary: PutSupplier
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                Name: Rezz
                Email: rezz@gmail.com
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Supplier
      summary: DeleteSupplier
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
